### ISSUE TITLE
Example Flow or at least properties to pass the node

### ISSUE THREAD

**Issue by DENightOne** [seth350/node-red-contrib-ui-lineargauge#2]
Hi there, would it be possible to have an really simple example flow, or at minimum a description of the properties to pass the node?

**Comment by DENightOne** [comment]
Sorry....found some more info here....but this uses the normal dashboard template node

https://flows.nodered.org/flow/2a4d688a42749e691c0d7eb5c0b870e3

I just copied the flow and change the template node with the new linear gauge node

**Comment by seth350** [comment]
Sorry about that, this is still very early in development. 
We have been working on developing this into an actual ui widget. 

You can place the code from the link you posted into a standard ui template and it will work. 
For the future, it will turn into a widget.
