### ISSUE TITLE
Setpoint

### ISSUE THREAD

**Issue by kskenyon** [seth350/node-red-contrib-ui-lineargauge#6]
Pointer stays at the top no matter where msg.setpoint is set.  msg.payload does not show at all.

latest update.

**Comment by seth350** [comment]
Sorry, just now seeing this. 

Latest is v0.3.1 for the linear gauge.

What version of Node-Red are you using? 
Dashboard version?
Web browser?

Here it is working on my box using the example flow. Let me know your version numbers and we will see if we can get it fixed for ya.
![image](https://user-images.githubusercontent.com/39222458/50752089-481bbf00-1212-11e9-95bf-1bab1ebeaa51.png)

**Comment by kskenyon** [comment]
See below

**Comment by seth350** [comment]
Is that Safari on mobile or PC?

I don’t get anything in Safari on my iPhone. 
If it’s on PC, I will do some testing. I always use Chrome.

**Comment by kskenyon** [comment]
MacBook Pro 15”-2017

Yep, works perfectly in Chrome, not in Safari.

Kevin

**Comment by seth350** [comment]
I’ll do some digging and see what I can figure out. Thanks for the heads up.

**Comment by seth350** [comment]
Naturally, I can only get Safari v5 for Windows 10. Apple quit supporting Safari for Windows back then. 
I emulated Safari in Edge and seems to work ok.

I don't know how I would test Safari outright without a Mac PC.

Check your web browser console log and see if there are any errors?

**Comment by kskenyon** [comment]
Note this error in the Javascript Console.  Might be a clue.  I’m not much of a coder.

Kevin

[Warning] ApplicationCache is deprecated. Please use ServiceWorkers instead. (ui, line 17)
[Log] Rendered http://10.0.1.32:1880/ui/css/app.min.less successfully. (app.min.js, line 499)
[Log] CSS for http://10.0.1.32:1880/ui/css/app.min.less generated in 334ms (app.min.js, line 499)
[Log] Less has finished. CSS generated in 335ms (app.min.js, line 499)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (angular-chart.min.js.map, line 0)
[Warning] You are using the ngTouch module.  (app.min.js, line 443)
AngularJS Material already has mobile click, tap, and swipe support... 
ngTouch is not supported with AngularJS Material!
[Log] Rendered http://10.0.1.32:1880/ui/css/app.min.less successfully. (app.min.js, line 499)
[Log] CSS for http://10.0.1.32:1880/ui/css/app.min.less generated in 128ms (app.min.js, line 499)
[Log] Less has finished. CSS generated in 128ms (app.min.js, line 499)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (angular-chart.min.js.map, line 0)

**Comment by seth350** [comment]
That error looks to be something missing within Node-Red. My gauge doesn't use the chart library. 
It is all svg graphics. 

The warnings are normal, I see the same thing with it working. 
Not sure what else to tell you other than to just use a different browser. Reinstall Safari maybe?
Any extensions that could cause some things not to load?

**Comment by kskenyon** [comment]
Looks like Chrome it is for now.  Not the end of the world for a dashboard.
Thanks for checking into it.

Kevin

**Comment by seth350** [comment]
No problem, sorry I couldn't help. 

If I may ask, how are you using the linear gauges? I'm just curious :)

**Comment by kskenyon** [comment]
I’m a retired chemical engineer and I’ve always liked controls displayed that way. Temperature, levels, lengths etc. Nothing very specific yet. 

They look old school like me. 

Kevin

Fatfingered from my iPhone

**Comment by seth350** [comment]
Thanks for sharing, and yes it makes it much easier and quicker to see who/what is performing correctly.
